repos:
  # AUTOFLAKE
  - hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
    repo: https://github.com/myint/autoflake
    rev: 'v1.4'
  # BLACK
  - hooks:
      - id: black
        language_version: python3
        args:
          - --line-length=80
    repo: https://github.com/psf/black
    rev: 20.8b1
  # DOCFORMATTER
  - hooks:
      - id: docformatter
        args:
          - -i
          - -r
          - --pre-summary-newline
          - --make-summary-multi-line
    repo: https://github.com/myint/docformatter
    rev: 'v1.4'
  # ISORT
  - hooks:
      - id: isort
        args:
          - --profile=black
          - --line-length=80
    repo: https://github.com/pycqa/isort
    rev: '5.7.0'
  # LOCAL HOOKS
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: .venv/bin/dmypy
        args:
          - check
          - src
        exclude: tests
        types:
          - python
      # pytest
      - id: pytest
        name: pytest
        language: system
        entry: .venv/bin/pytest
        args:
          - tests
        pass_filenames: false
        types:
          - python
